server:
  port: 8081

spring:
  application:
    name: gateway

  config:
    import: application-gateway-local.yml

  eureka:
    client:
      service-url:
        default-zone: http://localhost:8761/eureka

  cloud:
    gateway:
      routes:
        - id: user
          predicates:
            - Path=/users/user/**
          uri: lb://USER
          sensitive-headers: Cookie,Set-Cookie
          filters:
            - CustomAuthFilter
        - id: user
          predicates:
            - Path=/users/auth/**
          uri: lb://USER
          sensitive-headers: Cookie,Set-Cookie
        - id: payment
          predicates:
            - Path=/payments/**
          uri: lb://PAYMENT
          sensitive-headers: Cookie,Set-Cookie
        - id: funding
          predicates:
            - Path=/fundings/**
          uri: lb://FUNDING
          sensitive-headers: Cookie,Set-Cookie
        - id: reservation
          predicates:
            - Path=/reservations/**
          uri: lb://RESERVATION
          sensitive-headers: Cookie,Set-Cookie